name: Trigger auto deployment for serene-quick

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/serene-quick-AutoDeployTrigger-32298a68-6d67-4bda-841c-4a148d504e49.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENEQUICK_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: test
          registryUsername: ${{ secrets.SERENEQUICK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENEQUICK_REGISTRY_PASSWORD }}
          containerAppName: serene-quick
          resourceGroup: serene-env
          imageToBuild: test/dockergo:${{ github.sha }}
          

     

