name: Trigger auto deployment for serene-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/serene-test-AutoDeployTrigger-805ab785-1dea-4957-8522-026375529b1a.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENETEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: serene.azurecr.io
          registryUsername: ${{ secrets.SERENETEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENETEST_REGISTRY_PASSWORD }}
          containerAppName: serene-test
          resourceGroup: serene-env
          imageToBuild: serene.azurecr.io/serene-v2:${{ github.sha }}
          dockerfilePath: Dockerfile

     

