name: Trigger auto deployment for serene-ma

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '. /node-server/**'
    - '.github/workflows/serene-ma-AutoDeployTrigger-b71264c6-8dea-47dd-a598-d99083200291.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENEMA_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} /node-server 
          registryUrl: serene.azurecr.io
          registryUsername: ${{ secrets.SERENEMA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENEMA_REGISTRY_PASSWORD }}
          containerAppName: serene-ma
          resourceGroup: serene-ma
          imageToBuild: serene.azurecr.io/serene-ma:${{ github.sha }}
          
            

     

