name: Trigger auto deployment for serene-c

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/serene-c-AutoDeployTrigger-7ef3351f-650f-4084-9801-32d945265d2c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SERENEC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SERENEC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SERENEC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: sereneenvac4aa9.azurecr.io
          registryUsername: ${{ secrets.SERENEC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENEC_REGISTRY_PASSWORD }}
          containerAppName: serene-c
          resourceGroup: serene-env
          imageToBuild: sereneenvac4aa9.azurecr.io/serene-c:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


