name: Trigger auto deployment for serene

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/serene-AutoDeployTrigger-9ff89ae5-3554-4fdf-9dd7-3c3a1febf52d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: serene.azurecr.io
          username: ${{ secrets.SERENE_REGISTRY_USERNAME }}
          password: ${{ secrets.SERENE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: serene.azurecr.io/flaskproject:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n serene -g serene-fdaf --server serene.azurecr.io --username  ${{ secrets.SERENE_REGISTRY_USERNAME }} --password ${{ secrets.SERENE_REGISTRY_PASSWORD }}
            az containerapp update -n serene -g serene-fdaf --image serene.azurecr.io/flaskproject:${{ github.sha }}
