name: Trigger auto deployment for serene-quick

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '. /node-server/**'
    - '.github/workflows/serene-quick-AutoDeployTrigger-3f70d646-9c43-41dd-961e-1826c7ffe4ae.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENEQUICK_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} /node-server 
          registryUrl: serene.azurecr.io
          registryUsername: ${{ secrets.SERENEQUICK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENEQUICK_REGISTRY_PASSWORD }}
          containerAppName: serene-quick
          resourceGroup: serene-env
          imageToBuild: serene.azurecr.io/serene-quick:${{ github.sha }}
          
            

     

