name: Trigger auto deployment for serene

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '. /node-server/**'
    - '.github/workflows/serene-AutoDeployTrigger-261bf5f1-9bd0-4c87-a295-04a7cdd06018.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SERENE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} /node-server 
          registryUrl: serene4e721c.azurecr.io
          registryUsername: ${{ secrets.SERENE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERENE_REGISTRY_PASSWORD }}
          containerAppName: serene
          resourceGroup: serene-env
          imageToBuild: serene4e721c.azurecr.io/serene:${{ github.sha }}
          dockerfilePath: Dockerfile

     

